"""
Pydantic schemas for LOKAHOME API.
"""
from app.schemas.base import (
    BaseSchema,
    ErrorResponse,
    IDSchema,
    MessageResponse,
    PaginatedResponse,
    TimestampSchema,
)
from app.schemas.booking import (
    AvailabilityCheck,
    AvailabilityResponse,
    BookingCancellation,
    BookingCreate,
    BookingDetailResponse,
    BookingListResponse,
    BookingPriceCalculation,
    BookingResponse,
    BookingStatusUpdate,
    BookingUpdate,
)
from app.schemas.message import (
    ChatMessageResponse,
    ConversationCreate,
    ConversationListResponse,
    ConversationResponse,
    MarkNotificationsRead,
    MessageCreate,
    MessageListResponse,
    MessageReadReceipt,
    NotificationListResponse,
    NotificationPreferences,
    NotificationResponse,
    TypingIndicator,
    WebSocketMessage,
)
from app.schemas.payment import (
    FedaPayWebhook,
    MobileMoneyWebhook,
    PaymentCreate,
    PaymentInitResponse,
    PaymentListResponse,
    PaymentResponse,
    RefundRequest,
    RefundResponse,
    TransactionFilter,
    TransactionSummary,
)
from app.schemas.property import (
    NearbyPropertiesRequest,
    PropertyCreate,
    PropertyDetailResponse,
    PropertyImageCreate,
    PropertyImageResponse,
    PropertyListResponse,
    PropertyResponse,
    PropertySearchParams,
    PropertyUpdate,
)
from app.schemas.review import (
    ReviewCreate,
    ReviewFilter,
    ReviewListResponse,
    ReviewResponse,
    ReviewResponseCreate,
    ReviewSummary,
)
from app.schemas.service import (
    ServiceProviderCreate,
    ServiceProviderListResponse,
    ServiceProviderResponse,
    ServiceProviderSearchParams,
    ServiceProviderUpdate,
    ServiceQuoteCreate,
    ServiceQuoteListResponse,
    ServiceQuoteResponse,
    ServiceRequestCreate,
    ServiceRequestListResponse,
    ServiceRequestResponse,
    ServiceRequestSearchParams,
    ServiceRequestUpdate,
)
from app.schemas.user import (
    AdminUserUpdate,
    ChangePassword,
    PasswordResetConfirm,
    PasswordResetRequest,
    RefreshTokenRequest,
    TokenResponse,
    UserCreate,
    UserListResponse,
    UserLogin,
    UserProfileResponse,
    UserPublicProfile,
    UserRegister,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Base
    "BaseSchema",
    "IDSchema",
    "TimestampSchema",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    # User
    "UserLogin",
    "UserRegister",
    "TokenResponse",
    "RefreshTokenRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "ChangePassword",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserProfileResponse",
    "UserPublicProfile",
    "AdminUserUpdate",
    "UserListResponse",
    # Property
    "PropertyImageCreate",
    "PropertyImageResponse",
    "PropertyCreate",
    "PropertyUpdate",
    "PropertyResponse",
    "PropertyDetailResponse",
    "PropertyListResponse",
    "PropertySearchParams",
    "NearbyPropertiesRequest",
    # Booking
    "BookingCreate",
    "BookingUpdate",
    "BookingStatusUpdate",
    "BookingCancellation",
    "BookingResponse",
    "BookingDetailResponse",
    "BookingListResponse",
    "AvailabilityCheck",
    "AvailabilityResponse",
    "BookingPriceCalculation",
    # Payment
    "PaymentCreate",
    "PaymentInitResponse",
    "PaymentResponse",
    "PaymentListResponse",
    "FedaPayWebhook",
    "MobileMoneyWebhook",
    "RefundRequest",
    "RefundResponse",
    "TransactionFilter",
    "TransactionSummary",
    # Service
    "ServiceProviderCreate",
    "ServiceProviderUpdate",
    "ServiceProviderResponse",
    "ServiceProviderListResponse",
    "ServiceProviderSearchParams",
    "ServiceRequestCreate",
    "ServiceRequestUpdate",
    "ServiceRequestResponse",
    "ServiceRequestListResponse",
    "ServiceRequestSearchParams",
    "ServiceQuoteCreate",
    "ServiceQuoteResponse",
    "ServiceQuoteListResponse",
    # Message
    "ConversationCreate",
    "ConversationResponse",
    "ConversationListResponse",
    "MessageCreate",
    "ChatMessageResponse",
    "MessageListResponse",
    "NotificationResponse",
    "NotificationListResponse",
    "MarkNotificationsRead",
    "NotificationPreferences",
    "WebSocketMessage",
    "TypingIndicator",
    "MessageReadReceipt",
    # Review
    "ReviewCreate",
    "ReviewResponse",
    "ReviewListResponse",
    "ReviewResponseCreate",
    "ReviewSummary",
    "ReviewFilter",
]
