"""add_contracts_table

Revision ID: b098537a7a21
Revises: 5d61d35f917c
Create Date: 2026-02-27 21:57:59.305357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b098537a7a21"
down_revision: Union[str, None] = "5d61d35f917c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column(
            "contract_type",
            sa.Enum(
                "SHORT_TERM",
                "LONG_TERM",
                "FURNISHED",
                "UNFURNISHED",
                "SEASONAL",
                name="contracttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_LANDLORD",
                "PENDING_TENANT",
                "FULLY_SIGNED",
                "EXPIRED",
                "CANCELLED",
                name="contractstatus",
            ),
            nullable=False,
        ),
        sa.Column("draft_url", sa.String(length=500), nullable=True),
        sa.Column("signed_url", sa.String(length=500), nullable=True),
        sa.Column("landlord_signature_data", sa.Text(), nullable=True),
        sa.Column("landlord_signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("landlord_ip_address", sa.String(length=45), nullable=True),
        sa.Column("landlord_user_agent", sa.String(length=500), nullable=True),
        sa.Column("landlord_verification_code", sa.String(length=10), nullable=True),
        sa.Column("landlord_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_signature_data", sa.Text(), nullable=True),
        sa.Column("tenant_signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_ip_address", sa.String(length=45), nullable=True),
        sa.Column("tenant_user_agent", sa.String(length=500), nullable=True),
        sa.Column("tenant_verification_code", sa.String(length=10), nullable=True),
        sa.Column("tenant_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_hash", sa.String(length=64), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("special_conditions", sa.Text(), nullable=True),
        sa.Column("audit_log", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id"),
    )
    op.create_index(
        op.f("ix_contracts_reference"), "contracts", ["reference"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contracts_reference"), table_name="contracts")
    op.drop_table("contracts")
    # ### end Alembic commands ###
