"""add agent demarcheur tables and fields

Revision ID: e72ebd4ca6a5
Revises: b098537a7a21
Create Date: 2026-03-09 20:52:49.949049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e72ebd4ca6a5"
down_revision: Union[str, None] = "b098537a7a21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add AGENT to UserRole enum (between PROVIDER and ADMIN)
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'AGENT' BEFORE 'ADMIN'")

    # Add AGENT to ReviewType enum
    op.execute("ALTER TYPE reviewtype ADD VALUE IF NOT EXISTS 'AGENT' AFTER 'SERVICE_PROVIDER'")

    op.create_table(
        "agent_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("phone_whatsapp", sa.String(length=20), nullable=True),
        sa.Column("agent_code", sa.String(length=30), nullable=False),
        sa.Column(
            "service_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "specializations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("commission_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("identity_verified", sa.Boolean(), nullable=False),
        sa.Column("completed_deals", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("response_time_hours", sa.Integer(), nullable=True),
        sa.Column(
            "certifications", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "portfolio_images", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_agent_profiles_agent_code"),
        "agent_profiles",
        ["agent_code"],
        unique=True,
    )
    op.create_table(
        "agent_mandates",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("landlord_id", sa.UUID(), nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=True),
        sa.Column(
            "mandate_type",
            sa.Enum("EXCLUSIVE", "NON_EXCLUSIVE", "GLOBAL", name="mandatetype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVE", "EXPIRED", "REVOKED", name="mandatestatus"),
            nullable=False,
        ),
        sa.Column("commission_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["landlord_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "property_visits",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("visitor_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "COMPLETED", "CANCELLED", "NO_SHOW", name="visitstatus"
            ),
            nullable=False,
        ),
        sa.Column("visitor_feedback", sa.Text(), nullable=True),
        sa.Column("agent_notes", sa.Text(), nullable=True),
        sa.Column("resulted_in_booking", sa.Boolean(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["visitor_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("bookings", sa.Column("agent_id", sa.UUID(), nullable=True))
    op.add_column(
        "bookings",
        sa.Column(
            "agent_commission_rate", sa.Numeric(precision=5, scale=2), nullable=True
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "agent_commission_amount", sa.Numeric(precision=12, scale=2), nullable=True
        ),
    )
    op.add_column(
        "bookings",
        sa.Column("agent_commission_status", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "agent_commission_paid_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_foreign_key(
        None, "bookings", "agent_profiles", ["agent_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("payments", sa.Column("agent_id", sa.UUID(), nullable=True))
    commissiontype_enum = sa.Enum("PLATFORM", "AGENT", "LANDLORD", name="commissiontype")
    commissiontype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "payments",
        sa.Column(
            "commission_type",
            commissiontype_enum,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None, "payments", "agent_profiles", ["agent_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("reviews", sa.Column("agent_profile_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "reviews",
        "agent_profiles",
        ["agent_profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_column("reviews", "agent_profile_id")
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_column("payments", "commission_type")
    op.drop_column("payments", "agent_id")
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_column("bookings", "agent_commission_paid_at")
    op.drop_column("bookings", "agent_commission_status")
    op.drop_column("bookings", "agent_commission_amount")
    op.drop_column("bookings", "agent_commission_rate")
    op.drop_column("bookings", "agent_id")
    op.drop_table("property_visits")
    op.drop_table("agent_mandates")
    op.drop_index(op.f("ix_agent_profiles_agent_code"), table_name="agent_profiles")
    op.drop_table("agent_profiles")
    # ### end Alembic commands ###
