"""add reply_to_id to messages

Revision ID: 5d61d35f917c
Revises: 
Create Date: 2026-02-25 20:31:43.519725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d61d35f917c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("reply_to_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "messages", "messages", ["reply_to_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "reply_to_id")
    # ### end Alembic commands ###
